// Comprehensive Car Brands and Models Mapping
// Used for the Sell a Car feature to provide complete model lists

export const carBrandsWithModels = {
  'Maruti Suzuki': [
    'Alto',
    'Alto K10',
    'WagonR',
    'Celerio',
    'S-Presso',
    'Swift',
    'Swift Dzire',
    'Dzire',
    'Baleno',
    'Fronx',
    'Brezza',
    'Grand Vitara',
    'Ertiga',
    'XL6',
    'Ciaz',
    'Jimny',
    'Ignis',
    'Eeco',
    'S-Cross',
    'Ritz',
  ],
  Hyundai: [
    'i10',
    'Grand i10',
    'Grand i10 Nios',
    'i20',
    'i20 Active',
    'Verna',
    'Creta',
    'Venue',
    'Alcazar',
    'Tucson',
    'Aura',
    'Exter',
    'Santro',
    'Elantra',
    'Eon',
    'Kona Electric',
    'Ioniq 5',
  ],
  Tata: [
    'Tiago',
    'Tigor',
    'Altroz',
    'Punch',
    'Nexon',
    'Harrier',
    'Safari',
    'Curvv',
    'Bolt',
    'Zest',
    'Hexa',
    'Nano',
    'Indica',
    'Indigo',
    'Nexon EV',
    'Punch EV',
    'Tiago EV',
  ],
  Mahindra: [
    'Thar',
    'Thar Roxx',
    'XUV300',
    'XUV 3XO',
    'XUV700',
    'Scorpio',
    'Scorpio-N',
    'Scorpio Classic',
    'Bolero',
    'Bolero Neo',
    'XUV500',
    'XUV400 EV',
    'Marazzo',
    'TUV300',
    'KUV100',
    'Xylo',
  ],
  Honda: [
    'City',
    'City Hybrid',
    'Civic',
    'Accord',
    'Amaze',
    'Jazz',
    'WR-V',
    'CR-V',
    'BR-V',
    'Elevate',
    'Brio',
    'Mobilio',
  ],
  Toyota: [
    'Glanza',
    'Urban Cruiser',
    'Urban Cruiser Taisor',
    'Urban Cruiser Hyryder',
    'Innova Crysta',
    'Innova Hycross',
    'Fortuner',
    'Fortuner Legender',
    'Hilux',
    'Camry',
    'Vellfire',
    'Land Cruiser',
    'Etios',
    'Yaris',
    'Corolla Altis',
  ],
  Kia: [
    'Seltos',
    'Sonet',
    'Carens',
    'Carnival',
    'EV6',
    'EV9',
  ],
  Volkswagen: [
    'Polo',
    'Vento',
    'Taigun',
    'Virtus',
    'Tiguan',
    'Ameo',
    'Jetta',
    'Passat',
  ],
  Skoda: [
    'Kushaq',
    'Slavia',
    'Octavia',
    'Superb',
    'Kodiaq',
    'Rapid',
    'Laura',
    'Yeti',
  ],
  Renault: [
    'Kwid',
    'Triber',
    'Kiger',
    'Duster',
    'Pulse',
    'Scala',
    'Fluence',
    'Captur',
  ],
  BMW: [
    '3 Series',
    '5 Series',
    '7 Series',
    'X1',
    'X3',
    'X5',
    'X7',
    'iX',
    'Z4',
    'M340i',
  ],
  Audi: [
    'A3',
    'A4',
    'A6',
    'A8L',
    'Q3',
    'Q5',
    'Q7',
    'Q8',
    'e-tron',
    'RS e-tron GT',
  ],
  'Mercedes-Benz': [
    'A-Class',
    'C-Class',
    'E-Class',
    'S-Class',
    'GLA',
    'GLB',
    'GLC',
    'GLE',
    'GLS',
    'EQS',
    'AMG A35',
    'AMG C63',
  ],
  Jeep: [
    'Compass',
    'Meridian',
    'Wrangler',
    'Grand Cherokee',
  ],
  MG: [
    'Astor',
    'Hector',
    'Hector Plus',
    'ZS EV',
    'Comet EV',
    'Gloster',
    'Windsor EV',
  ],
  'Land Rover': [
    'Defender',
    'Discovery',
    'Discovery Sport',
    'Range Rover Evoque',
    'Range Rover Velar',
    'Range Rover Sport',
    'Range Rover',
  ],
  Nissan: [
    'Magnite',
    'Kicks',
    'Sunny',
    'Micra',
    'Terrano',
    'GT-R',
    'X-Trail',
  ],
  Ford: [
    'EcoSport',
    'Endeavour',
    'Figo',
    'Aspire',
    'Mustang',
    'Fiesta',
    'Freestyle',
  ],
  Fiat: [
    'Punto',
    'Linea',
    'Punto Evo',
    'Avventura',
    'Abarth Punto',
  ],
  Chevrolet: [
    'Beat',
    'Cruze',
    'Sail',
    'Spark',
    'Tavera',
    'Captiva',
    'Enjoy',
  ],
  Volvo: [
    'XC40',
    'XC60',
    'XC90',
    'S90',
    'C40 Recharge',
    'V40',
  ],
  Jaguar: [
    'XE',
    'XF',
    'F-Pace',
    'F-Type',
    'I-Pace',
  ],
  Lexus: [
    'ES',
    'NX',
    'RX',
    'LX',
    'LS',
    'LC',
  ],
  Porsche: [
    '911 Carrera',
    'Cayenne',
    'Macan',
    'Panamera',
    'Taycan',
    '718 Boxster',
    '718 Cayman',
  ],
  'Mini Cooper': [
    'Cooper 3-Door',
    'Cooper 5-Door',
    'Cooper Countryman',
    'Cooper Convertible',
    'Clubman',
  ],
  Citroen: [
    'C3',
    'C3 Aircross',
    'C5 Aircross',
    'Basalt',
    'eC3',
  ],
  Datsun: [
    'Go',
    'Go Plus',
    'Redi-Go',
  ],
  Isuzu: [
    'D-Max V-Cross',
    'MU-X',
    'S-Cab',
  ],
  Force: [
    'Gurkha',
    'Trax',
    'Cruiser',
  ],
  Mitsubishi: [
    'Pajero',
    'Pajero Sport',
    'Outlander',
    'Lancer',
    'Montero',
  ],
  Suzuki: [
    'Swift',
    'Baleno',
    'Dzire',
    'Brezza',
    'Ertiga',
    'Alto',
    'WagonR',
  ],
  Mazda: [
    'Mazda2',
    'Mazda3',
    'Mazda6',
    'CX-5',
    'MX-5 Miata',
  ],
  GMC: [
    'Yukon',
    'Sierra',
    'Acadia',
  ],
  Mopar: [
    'RAM 1500',
    'Jeep Wrangler',
    'Jeep Compass',
  ]
};

// Get models for a specific brand
export const getModelsByBrand = (brand) => {
  return carBrandsWithModels[brand] || [];
};

// Get all available brands
export const getAllBrandsWithModels = () => {
  return Object.keys(carBrandsWithModels);
};

// Check if a model exists for a brand
export const isValidModel = (brand, model) => {
  const models = carBrandsWithModels[brand] || [];
  return models.includes(model);
};
